# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  codemirror = nodeEnv.buildNodePackage {
    name = "codemirror";
    packageName = "codemirror";
    version = "5.42.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/codemirror/-/codemirror-5.42.0.tgz";
      sha512 = "pbApC8zDzItP3HRphD6kQVwS976qB5Qi0hU3MZMixLk+AyugOW1RF+8XJEjeyl5yWsHNe88tDUxzeRh5AOxPRw==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Full-featured in-browser code editor";
      homepage = https://codemirror.net/;
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
}
